/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ablums: typeof import('./src/components/music/music/ablums.vue')['default']
    BottomPopUp: typeof import('./src/components/bottomPopUp.vue')['default']
    Collection: typeof import('./src/components/music/music/collection.vue')['default']
    CollectToCreate: typeof import('./src/components/collectToCreate.vue')['default']
    Create: typeof import('./src/components/music/music/create.vue')['default']
    HelloQ: typeof import('./src/components/helloQ.vue')['default']
    IndexBlog: typeof import('./src/components/blog/indexBlog.vue')['default']
    IndexMoment: typeof import('./src/components/moments/indexMoment.vue')['default']
    IndexMusic: typeof import('./src/components/music/indexMusic.vue')['default']
    Music: typeof import('./src/components/music/index.vue')['default']
    NewCreate: typeof import('./src/components/newCreate.vue')['default']
    Recent: typeof import('./src/components/music/music/recent.vue')['default']
    Reply: typeof import('./src/components/reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongHistory: typeof import('./src/components/songHistory.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanList: typeof import('vant/es')['List']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
